apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yz47335of-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/yz47335of-dotnet-basic